PatchTracker: Fix pointer allocation in searchNCCTemplate
This was causing TestLocalizer to segfault when patchsearch was being
performed without "subsample".

  $ TestLocalizer village2-11 village17.xml 100
  done reading xml
  done reading descriptors
  done reading images
  done making approxNN
  making averaged descriptors
  done making averaged descriptors
  running query with 6823 features
  done matching
  346 matches for pose estimation
  346 matches; 74 inliers
  OpenCV Error: Assertion failed (total() == 0 || data != NULL) in Mat, file
  /usr/local/include/opencv2/core/mat.inl.hpp, line 447
  terminate called after throwing an instance of 'cv::Exception'
    what():  /usr/local/include/opencv2/core/mat.inl.hpp:447: error: (-215)
  total() == 0 || data != NULL in function Mat

  Aborted (core dumped)